### ISSUE TITLE
Feature #1: As a student, I want to differentiate between student, TA, and instructor replies, so that I am aware of which identity the response comes from.

### ISSUE THREAD

**Issue by monicaq21** [CMU-313/fall23-nodebb-consonants-compadres#1]
Adding a new label system 
Adding a new query system 
Add new UI for distinction between user roles

**Comment by derekk10** [comment]
Estimated time: 40 total hours

**Comment by lwei11** [comment]
Estimated effort for each task
Dependencies among tasks (if any)
Initial assignments for team members
Milestones to indicate which sprint the issue should be completed in (Sprint 1, Sprint 2, Stretch)
Acceptance criteria that describes how you know this task is done - think about how you will test this feature
